// AUTOGENERATED FILE

package main

import (
	"fullStack-news-discord-bot/src/internal"
	"github.com/aws/aws-lambda-go/lambda"
)

func main() {
	createEventRestController := internal.InitializeCreateEventRestController()
	lambda.Start(createEventRestController.HandleLambdaEvent)
}
